### ISSUE TITLE
setting up a cross-compiler for armv7 with crossdev fails with: ../image//usr/lib64/libcc1*': No such file or directory

### ISSUE THREAD

**Issue by stefson** [gentoo/musl#245] opened 2019-07-07 08:27 UTC
this used to work in the past: 

crossdev -S armv7a-unknown-linux-musleabihf --binutils 2.32-r1

compressed build log: [gcc-8.3.0-fails-to-move-libcc1.log.gz](https://github.com/gentoo/musl/files/3365384/gcc-8.3.0-fails-to-move-libcc1.log.gz)

this also works for a glibc host, can this be caused by the new gcc-pure64.patch?

**Comment by blueness** [comment] 2019-07-07 10:26
It is possible since `/usr/lib64/libcc1*` should be at `/usr/lib/libcc1*` in the sysroot.  The gcc-pure64.patch was a hack until upstream address the issues, which may take forever.  Try to comment out that patch and see what happens.

**Comment by stefson** [comment] 2019-07-07 11:21
I can confirm that `sys-devel/gcc` has to be emerged without the patch, it never applied to the cross-gcc for armv7 anyway.

**Comment by xuefer** [comment] 2020-03-27 12:38
how to get around this problem?

**Comment by anarchpenguin** [comment] 2020-03-27 12:55
You have to modify toolchain.eclass to use a hardcoded libdir for libcc1. I have not really took the time to review crossdev to find a proper solution as of yet.

**Comment by anarchpenguin** [comment] 2020-03-27 15:09
https://gist.github.com/anarchpenguin/62f952b3652e7e1b75671ea568e176b6 

I am waiting to hear back from slyfox on this, if you all want to test it feel free, I did test it with aarch64 cross toolchain.

**Comment by xuefer** [comment] 2020-03-27 15:16
thanks for the patch. i'll use it

i'm noob on this, but the thing is, while lib64 comes from your aarch64, it shouldn't appears on my arm 32bit build (compiler host is x86_64)

**Comment by xuefer** [comment] 2020-03-27 16:26
> https://gist.github.com/anarchpenguin/62f952b3652e7e1b75671ea568e176b6
> 
> I am waiting to hear back from slyfox on this, if you all want to test it feel free, I did test it with aarch64 cross toolchain.

i'm sorry to say it still fail after your patch
```
# crossdev  --stable --target arm-linux-musleabihf
* Log: /var/log/portage/cross-arm-linux-musleabihf-binutils.log
* Emerging cross-binutils ...
* Log: /var/log/portage/cross-arm-linux-musleabihf-gcc-stage1.log
* Emerging cross-gcc-stage1 ...
```
fail at this step, musl is not even

i try stupid fallback:
`mv "${ED}"/usr/$(get_libdir)/libcc1* "${D}${HOSTLIBPATH}" || mv "${ED}"/usr/lib/libcc1* "${D}${HOSTLIBPATH}" || die`
after this change it pass until cross-musl

```
* Emerging cross-musl ...
 * error: musl failed :(
```
```
using compiler runtime libraries: -lgcc -lgcc_eh
checking preprocessor condition __thumb2__... false
checking preprocessor condition __ARMEB__... false
checking preprocessor condition __ARM_PCS_VFP... false
checking whether clang's vfp asm constraints work... yes
checking whether compiler's long double definition matches float.h... no
./configure: error: unsupported long double type
```

**Comment by trofi** [comment] 2020-03-27 19:08
A few points:

1. `multilib.eclass` will need a fix to add musl-specific `lib` layout: https://gitweb.gentoo.org/repo/gentoo.git/tree/eclass/multilib.eclass#n298. I'll try to reproduce locally and tweak it.

2. `arm-linux-musleabihf` is propbably **not the target you want**. I suggest picking one from gentoo's profiles, like `armv7a-unknown-linux-musleabihf`. Otherwise you get very old ARMv1 ISA (or whatever is the lowest toolchain).

**Comment by trofi** [comment] 2020-03-27 22:41
Another discrepancy is that `gcc-pure64.patch` does **not** get applied to cross-compilers, but it **should**:

```bash
src_prepare() {
	toolchain_src_prepare

	if use elibc_musl || [[ ${CATEGORY} = cross-*-musl* ]]; then
		eapply "${FILESDIR}"/6.3.0/cpu_indicator.patch
		eapply "${FILESDIR}"/7.1.0/posix_memalign.patch
		case $(tc-arch) in
			amd64|arm64|ppc64) eapply "${FILESDIR}"/8.3.0/gcc-pure64.patch ;;
		esac
	fi

	eapply_user
}
```

Specifically `$(tc-arch)` returns target's `arm` arch, not host's arch.

Conditionally applying patches to driver is almost never correct: you get different behaviour of a stage1 intermediate `gcc` binary between native and cross case. Even it they are both intended for the same ${CBUILD} (as in this case).

Ideal fix would be to rework `gcc-pure64.patch` to apply libdir overrides only for '*-musl*' ports within gcc's source code.

**Comment by trofi** [comment] 2020-03-28 00:18
https://github.com/gentoo/gentoo/commit/26578a15abfca9149f296c33b754fa195e0ccf9b should sort out `multilib_env` default in `crossdev`.

I'm not sure if it's enough to fix all the cases. Worth a try.

**Comment by anarchpenguin** [comment] 2020-03-28 01:30
> Another discrepancy is that `gcc-pure64.patch` does **not** get applied to cross-compilers, but it **should**:
> 
> ```shell
> src_prepare() {
> 	toolchain_src_prepare
> 
> 	if use elibc_musl || [[ ${CATEGORY} = cross-*-musl* ]]; then
> 		eapply "${FILESDIR}"/6.3.0/cpu_indicator.patch
> 		eapply "${FILESDIR}"/7.1.0/posix_memalign.patch
> 		case $(tc-arch) in
> 			amd64|arm64|ppc64) eapply "${FILESDIR}"/8.3.0/gcc-pure64.patch ;;
> 		esac
> 	fi
> 
> 	eapply_user
> }
> ```
> 
> Specifically `$(tc-arch)` returns target's `arm` arch, not host's arch.
> 
> Conditionally applying patches to driver is almost never correct: you get different behaviour of a stage1 intermediate `gcc` binary between native and cross case. Even it they are both intended for the same ${CBUILD} (as in this case).
> 
> Ideal fix would be to rework `gcc-pure64.patch` to apply libdir overrides only for '_-musl_' ports within gcc's source code.

the patch is applied for 64bit archs, I just confirmed it again.I tested both arm64 and ppc64

**Comment by trofi** [comment] 2020-03-28 08:55
But `arm` is not a 64-bit arch. And you want that patch applied, if host is 64-bit regardless of target.

**Comment by anarchpenguin** [comment] 2020-04-12 19:33
> But `arm` is not a 64-bit arch. And you want that patch applied, if host is 64-bit regardless of target.

This has already been fixed in tree.

commit 26578a15abfca9149f296c33b754fa195e0ccf9b
Author: Sergei Trofimovich <slyfox@gentoo.org>
Date:   Fri Mar 27 23:47:15 2020 +0000

    multilib.eclass: multilib_env(): set LIBDIR=lib for *-musl*
    
    In contrast to glibc musl profiles use 'lib' layour for 32-bit
    and 64-bit targets. multilib_env() did not take it into account
    and assumed glibc's lib64 layout.
    
    That breaks crossdev as it uses multilib_env to extract target
    definition. Native builds are unaffected by this change.
    
    Bug: https://bugs.gentoo.org/675954
    Bug: https://gcc.gnu.org/PR90077
    Bug: https://github.com/gentoo/musl/issues/245
    Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>

diff --git a/eclass/multilib.eclass b/eclass/multilib.eclass
index 63bde5cbb60..8b4a7dacaa3 100644
--- a/eclass/multilib.eclass
+++ b/eclass/multilib.eclass
@@ -294,11 +294,22 @@ get_modname() {
 }
 
 # This is for the toolchain to setup profile variables when pulling in
-# a crosscompiler (and thus they aren't set in the profile)
+# a crosscompiler (and thus they aren't set in the profile).
 multilib_env() {
        local CTARGET=${1:-${CTARGET}}
        local cpu=${CTARGET%%*-}
 
+       if [[ ${CTARGET} = *-musl* ]]; then
+               # musl has no multilib support and can run only in 'lib':
+               # - https://bugs.gentoo.org/675954
+               # - https://gcc.gnu.org/PR90077
+               # - https://github.com/gentoo/musl/issues/245
+               : ${MULTILIB_ABIS=default}
+               : ${DEFAULT_ABI=default}
+               export MULTILIB_ABIS DEFAULT_ABI
+               return
+       fi
+
        case ${cpu} in
                aarch64*)
                        # Not possible to do multilib with aarch64 and a single toolchain.

**Closed by anarchpenguin** 2020-04-12 19:33 UTC
