### ISSUE TITLE
Segfaults with mesa-18.1.0_rc*

### ISSUE THREAD

**Issue by lluixhi** [gentoo/musl#136] opened 2018-05-03 18:40 UTC
It seems something in mesa must've broken -- presumably with musl, as applications that use OpenGL are segfaulting.

This isn't a problem pre-18.1.0

**Comment by blueness** [comment] 2018-05-03 19:18
can you give me steps to reproduce?  i need to see what's causing the seg fault.

**Comment by lluixhi** [comment] 2018-05-04 19:02
mesa USE="classic dri3 egl gbm gles2 pic vulkan wayland" VIDEO_CARDS="i965 intel"

dmesg:
[20006.793663] guvcview[1581]: segfault at 7f27651ca698 ip 00007f2755d2f9b0 sp 00007f27651ca698 error 6 in i965_dri.so[7f27556f1000+a40000]
[20055.387983] mpv/vo[1714]: segfault at 7fa05d0c17d8 ip 00007fa05d8569b0 sp 00007fa05d0c17d8 error 6 in i965_dri.so[7fa05d218000+a40000]

Interestingly, Firefox and X11 works regardless, so presumably just some OpenGL functions are broken, and it might be an intel specific problem. I didn't

**Comment by blueness** [comment] 2018-05-05 09:11
can you use gdb and give me a stack trace so we can see where this breaks.  alternatively, can you give me an strace.

**Comment by anarchpenguin** [comment] 2018-05-31 14:32
https://cgit.freedesktop.org/xorg/xserver/commit/?id=352a5ac87fd344936b759a5766eb74271e7d295d

Please read entirely.

**Comment by lluixhi** [comment] 2018-06-02 00:47
@anarchpenguin ah, alright. My fault for using xf86-video-intel then. Thanks.

**Comment by lluixhi** [comment] 2018-06-04 22:07
oof nevermind, switching back to modesetting, trying different versions of xorg, etc. doesn't work.

This is an issue in mesa, as far as i can tell.

**Comment by saih792** [comment] 2018-10-07 11:28
See https://bugs.freedesktop.org/show_bug.cgi?id=35268

Increasing the stack size does not actually solve the issue, it just increases the threshold at which segfaults occur. The problem is that mesa misuses the initial-exec mode for TLS in order to increase performance, and glibc has been complicit in this by allocating extra TLS space specifically for GL to use in this way. The real solution is to use global-dynamic mode and then make up for the performance hit by using TLSDESC (i.e. -mtls-dialect=gnu2 which is supported by both musl and clang). However, this requires a lot of changes throughout the code in places where the use of initial-exec mode is assumed, and should really be done by upstream. Unfortunatley that doesn't look like it's going to happen given that this has been an issue for over 7 years.

**Comment by anarchpenguin** [comment] 2019-07-13 20:51
This has been fixed in 19.1.2 which corrects the buffer.

**Comment by anarchpenguin** [comment] 2019-10-21 14:10
We can close this now, 19.x is stable and has the appropriate upstream patches in it already.

**Closed** 2019-12-05 16:52 UTC
